on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        env:
          CODECOV_TOKEN: 2bc37bd4-980f-4f56-b981-e42f419a2ac7
        run: |
          go test -v github.com/averageflow/gohooks/v2/tests/... -coverpkg=github.com/averageflow/gohooks/v2/... -coverprofile=coverage.out ./... ./...
          curl -s https://codecov.io/bash | bash